---
# ====== Application: MyApp ==================================
identification: 
  name: MyApp
  alias: MYAPP
  version: Release 1.0

row-search: 
  tokenize: true
  text-query-function: None

availability: 
  status: Available with Developer Toolbar
  build-status: Run and Build Application

error-handling: 
  default-display-location: Inline with Field and in Notification

report-printing: 
  type: Use Instance Settings

advanced: 
  friendly-urls: true
  allow-feedback: true
  logging: true
  debugging: false
  compatibility-mode: 21.2 to 24.1
  accessible-read-only-items: true
  pass-ecid: Y

authentication: 
  public-user: APEX_PUBLIC_USER
  authentication-scheme: custom # 38957699495330541934

authorization: 
  source-for-role-or-group-schemes: Access Control User Role Assignments

session-management: 
  rejoin-sessions: Disabled

session-state-protection: 
  enabled: true

security: 
  deep-linking: Disabled
  browser-cache: Disabled
  embed-in-frames: Deny
  referrer-policy: strict-origin
  html-escaping-mode: Extended

database-session: 
  parsing-schema: WKSP_DEVENV

globalization: 
  primary-language: English (en)
  document-direction: Left-To-Right
  language-derived-from: Application Primary Language
  automatic-time-zone: false
  automatic-csv-encoding: true

application-format-masks: 
  date: DS
  timestamp: DS
  timestamp-time-zone: DS

character-value-comparison: 
  behavior: Database session NLS setting (default)

logo: 
  type: Text
  text: MyApp

progressive-web-app: 
  enable: true
  installable: false
  display: Standalone
  screen-orientation: Any
  ios-status-bar-style: Default
  enable-push-notifications: false

navigation: 
  home-url: 
    url: 'f?p=&APP_ID.:1:&APP_SESSION.::&DEBUG.:::'
    page: 1

  login-url: 
    url: 'f?p=&APP_ID.:LOGIN:&APP_SESSION.::&DEBUG.:::'
    page: LOGIN

navigation-menu: 
  list-template: Top Navigation Menu
  template-options: 
  - '#DEFAULT#'
  - js-tabLike
  list-position: Top

navigation-bar: 
  implementation: List
  list: Navigation Menu # 38956527280018503888

javascript: 
  include-jquery-migrate: false

attributes: 
  theme: Universal Theme # 42
  global-page: 0
  enable-end-users-to-choose-theme-style: false
  add-"built-with-apex"-to-footer: false
  auto-dismiss-success-messages: false

substitutions: 
- # ====== Substitution: APP_NAME ==============================
  id: 1
  identification: 
    name: APP_NAME

  value: 
    static-value: MyApp

component-settings: 
- # ====== Component Setting: NATIVE_OPEN_AI_ASSISTANT =========
  id: 38956522283687503884
  identification: 
    name: NATIVE_OPEN_AI_ASSISTANT
    type: Dynamic Action

  subscription: 
    version-number: 15569935879613

- # ====== Component Setting: NATIVE_COLOR_PICKER ==============
  id: 38956522503261503885
  identification: 
    name: NATIVE_COLOR_PICKER
    type: Item

  settings: 
    attribute-1: FULL
    attribute-2: POPUP

  subscription: 
    version-number: 15569935879659

- # ====== Component Setting: NATIVE_DATE_PICKER_APEX ==========
  id: 38956522881477503885
  identification: 
    name: NATIVE_DATE_PICKER_APEX
    type: Item

  settings: 
    attribute-1: 'MONTH-PICKER:YEAR-PICKER:TODAY-BUTTON'
    attribute-2: VISIBLE
    attribute-3: 15
    attribute-4: FOCUS

  subscription: 
    version-number: 15569935879690

- # ====== Component Setting: NATIVE_GEOCODED_ADDRESS ==========
  id: 38956523181063503885
  identification: 
    name: NATIVE_GEOCODED_ADDRESS
    type: Item

  settings: 
    attribute-1: RELAX_HOUSE_NUMBER
    attribute-2: N
    attribute-3: 'POPUP:ITEM'
    attribute-4: default
    attribute-6: LIST

  subscription: 
    version-number: 15569935879725

- # ====== Component Setting: NATIVE_SELECT_MANY ===============
  id: 38956523475176503885
  identification: 
    name: NATIVE_SELECT_MANY
    type: Item

  settings: 
    attribute-1: separated

  subscription: 
    version-number: 15569935879755

- # ====== Component Setting: NATIVE_SINGLE_CHECKBOX ===========
  id: 38956523713497503885
  identification: 
    name: NATIVE_SINGLE_CHECKBOX
    type: Item

  settings: 
    attribute-1: Y
    attribute-2: N

  subscription: 
    version-number: 15569935879776

- # ====== Component Setting: NATIVE_STAR_RATING ===============
  id: 38956524017949503886
  identification: 
    name: NATIVE_STAR_RATING
    type: Item

  settings: 
    attribute-1: fa-star
    attribute-4: '#VALUE#'

  subscription: 
    version-number: 15569935879800

- # ====== Component Setting: NATIVE_YES_NO ====================
  id: 38956524376312503886
  identification: 
    name: NATIVE_YES_NO
    type: Item

  settings: 
    attribute-1: Y
    attribute-3: N
    attribute-5: SWITCH_CB

  subscription: 
    version-number: 15569935879832

- # ====== Component Setting: NATIVE_GEOCODING =================
  id: 38956524614092503886
  identification: 
    name: NATIVE_GEOCODING
    type: Process

  settings: 
    attribute-1: RELAX_HOUSE_NUMBER

  subscription: 
    version-number: 15569935879858

- # ====== Component Setting: NATIVE_DISPLAY_SELECTOR ==========
  id: 38956524945567503886
  identification: 
    name: NATIVE_DISPLAY_SELECTOR
    type: Region

  subscription: 
    version-number: 15569935879887

- # ====== Component Setting: NATIVE_IR ========================
  id: 38956525282196503886
  identification: 
    name: NATIVE_IR
    type: Region

  subscription: 
    version-number: 15569935879935

- # ====== Component Setting: NATIVE_MAP_REGION ================
  id: 38956525510517503886
  identification: 
    name: NATIVE_MAP_REGION
    type: Region

  subscription: 
    version-number: 15569935879964

- # ====== Component Setting: NATIVE_ADFBC =====================
  id: 38956525837882503887
  identification: 
    name: NATIVE_ADFBC
    type: REST Data Source

  subscription: 
    version-number: 15569935879996

